### ISSUE TITLE
J'ai oublié est ce qu'on peut faire des dumps de $  même si Profiler est installé?

### ISSUE THREAD

**Issue by Juju075** [Juju075/snowtricks2#12]

**Comment by itahriouan1** [comment]
il faut utiliser le dumper de symfony:
installer symfony/var-dumper
utiliser dans un controller par exemple:
```
$obj= new stdClass();
        $obj->Name='nom';
        $obj->Age=23;
        dump($obj);
```
ouvrir la route du controller, aller vers profiler et chercher debug dans le menu à gauche

**Comment by Juju075** [comment]
ok Merci
