### ISSUE TITLE
[ FRONTEND]How to style twig form with boostrap?

### ISSUE THREAD

**Issue by Juju075** [Juju075/snowtricks2#40]

**Comment by itahriouan1** [comment]
in twig you can easily personalize form element this way:

{{ form_widget(form.name, {'attr':{'class': 'bootstrap-tag'}}) }}

in this example "name" is the name of the form element

good luck

**Comment by Juju075** [comment]
ok

**Comment by Juju075** [comment]
ok

**Comment by Juju075** [comment]
https://symfony.com/doc/current/form/bootstrap5.html
*****************************
