### ISSUE TITLE
[ Soutenance correction ] @app_edit    | edit/delete photo - videos | Submit  /  Method Not Allowed (Allow: DELETE)

### ISSUE THREAD

**Issue by Juju075** [Juju075/snowtricks2#66]
HTML forms do not support PUT, PATCH or DELETE actions.
*****************************
Laravel
So, when defining PUT, PATCH or DELETE routes that are called from an HTML form, 
you will need to add a hidden _method field to the form. The value sent with 
the _method field will be used as the HTTP request method:

<form action="/foo/bar" method="POST">
    <input type="hidden" name="_method" value="PUT">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
</form>

**Comment by Juju075** [comment]
405 Method Not Allowed
Le code de statut de réponse HTTP 405 Method Not Allowed indique que la méthode utilisée pour la requête est connue du serveur mais qu'elle n'est pas supportée par la ressource ciblée.

**Comment by NaincyKumariKnoldus** [comment]
Hey @Juju075 Can I do this?

**Comment by Juju075** [comment]
Hi @ NaincyKumariKnoldus

**Comment by Juju075** [comment]
Resolved
